id: IC6DBABE6
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-08-16T14:22:26.667099'
last_modified: '2022-08-16T14:22:26.667110'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: bo
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
